version: '3'

services:
  mongo:
    image: mongo:3.4
    networks:
      default:
        aliases:
          - mongo
    volumes:
      - /data/mongo-db-data:/data/db
    ports:
      - "27017:27017"
  backend:
    build:
      context: .
      dockerfile: dockerbuild/Dockerfile-backend
    volumes:
      - /data/sql-data/modeldb.db:/modeldb/server/modeldb.db
    image: mitdbg/modeldb-backend:latest
    networks:
      default:
        aliases:
          - backend
    ports:
      - "6543:6543"
    command: ["mongo"]
  frontend:
    build:
      context: .
      dockerfile: dockerbuild/Dockerfile-frontend
    image: mitdbg/modeldb-frontend:latest
    networks:
      default:
        aliases:
          - frontend
    ports:
      - "3000:3000"
    command: ["backend"]
